// vue-components/resources/component-template.vue
<template>
  <div :class="['relative', props.class]">
    <slot />
  </div>
</template>

<script setup lang="ts">
// Use a valid identifier like 'StitchComponent' as the placeholder.
// Replace ALL occurrences of 'StitchComponent' with the actual component name.

interface StitchComponentProps {
  class?: string;
}

const props = withDefaults(defineProps<StitchComponentProps>(), {
  class: "",
});
</script>

// skills/react-components/resources/component-template.tsx
import React from 'react';

// Use a valid identifier like 'StitchComponent' as the placeholder
interface StitchComponentProps {
  readonly children?: React.ReactNode;
  readonly className?: string;
}

export const StitchComponent: React.FC<StitchComponentProps> = ({
  children,
  className = '',
  ...props
}) => {
  return (
    <div className={`relative ${className}`} {...props}>
      {children}
    </div>
  );
};

export default StitchComponent;
